// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountProducts(ctx context.Context) (int64, error)
	CreateCartItem(ctx context.Context, arg CreateCartItemParams) (Cart, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductMedia(ctx context.Context, arg CreateProductMediaParams) (ProductMedium, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShippingAddress(ctx context.Context, arg CreateShippingAddressParams) (ShippingAddress, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteCartItem(ctx context.Context, productID int32) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteProductMedia(ctx context.Context, productID string) error
	GetCartItem(ctx context.Context, id int64) (Cart, error)
	GetCartItemByProductId(ctx context.Context, productID int32) (Cart, error)
	GetCartItemByUser(ctx context.Context, userRefID int64) (Cart, error)
	GetCollection(ctx context.Context, id int64) (Collection, error)
	GetMedia(ctx context.Context, id int64) (Medium, error)
	GetMediaByRef(ctx context.Context, mediaRef string) (Medium, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	GetOrderItem(ctx context.Context, id int64) (OrderItem, error)
	GetOrderItemsForOrder(ctx context.Context, arg GetOrderItemsForOrderParams) ([]OrderItem, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductMedia(ctx context.Context, id int64) (ProductMedium, error)
	GetProductMediaByRef(ctx context.Context, productMediaRef string) (ProductMedium, error)
	GetProductsMedium(ctx context.Context, arg GetProductsMediumParams) ([]ProductMedium, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetShippingAddress(ctx context.Context, id int64) (ShippingAddress, error)
	GetUser(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserOrders(ctx context.Context, arg GetUserOrdersParams) ([]Order, error)
	GetUserShippingAddresses(ctx context.Context, arg GetUserShippingAddressesParams) ([]ShippingAddress, error)
	ListCartItems(ctx context.Context, arg ListCartItemsParams) ([]Cart, error)
	ListCollection(ctx context.Context, arg ListCollectionParams) ([]Collection, error)
	ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error)
	ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItem, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListProductMedia(ctx context.Context, arg ListProductMediaParams) ([]ProductMedium, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListShippingAddresses(ctx context.Context, arg ListShippingAddressesParams) ([]ShippingAddress, error)
	ListUserCartItems(ctx context.Context, arg ListUserCartItemsParams) ([]Cart, error)
	UpdateCartItemQty(ctx context.Context, arg UpdateCartItemQtyParams) (Cart, error)
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserVerificationCode(ctx context.Context, arg UpdateUserVerificationCodeParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
