// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductMedia(ctx context.Context, arg CreateProductMediaParams) (ProductMedium, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	GetCollection(ctx context.Context, id int64) (Collection, error)
	GetMedia(ctx context.Context, id int64) (Medium, error)
	GetMediaByRef(ctx context.Context, mediaRef string) (Medium, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductMedia(ctx context.Context, id int64) (ProductMedium, error)
	GetProductMediaByRef(ctx context.Context, productMediaRef string) (ProductMedium, error)
	GetProductsMedium(ctx context.Context, arg GetProductsMediumParams) ([]ProductMedium, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListCollection(ctx context.Context, arg ListCollectionParams) ([]Collection, error)
	ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error)
	ListProductMedia(ctx context.Context, arg ListProductMediaParams) ([]ProductMedium, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
