// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  hashed_password,
  first_name,
  last_name,
  phone_number,
  profile_photo,
  email,
  is_admin
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING username, hashed_password, first_name, last_name, phone_number, profile_photo, email, is_admin, password_changed_at, created_at, is_email_verified, id, verification_code
`

type CreateUserParams struct {
	Username       string      `json:"username"`
	HashedPassword string      `json:"hashed_password"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	PhoneNumber    string      `json:"phone_number"`
	ProfilePhoto   pgtype.Text `json:"profile_photo"`
	Email          string      `json:"email"`
	IsAdmin        bool        `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.ProfilePhoto,
		arg.Email,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfilePhoto,
		&i.Email,
		&i.IsAdmin,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
		&i.ID,
		&i.VerificationCode,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, hashed_password, first_name, last_name, phone_number, profile_photo, email, is_admin, password_changed_at, created_at, is_email_verified, id, verification_code FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfilePhoto,
		&i.Email,
		&i.IsAdmin,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
		&i.ID,
		&i.VerificationCode,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT username, hashed_password, first_name, last_name, phone_number, profile_photo, email, is_admin, password_changed_at, created_at, is_email_verified, id, verification_code FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfilePhoto,
		&i.Email,
		&i.IsAdmin,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
		&i.ID,
		&i.VerificationCode,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT username, hashed_password, first_name, last_name, phone_number, profile_photo, email, is_admin, password_changed_at, created_at, is_email_verified, id, verification_code FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfilePhoto,
		&i.Email,
		&i.IsAdmin,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
		&i.ID,
		&i.VerificationCode,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  hashed_password = COALESCE($1, hashed_password),
  password_changed_at = COALESCE($2, password_changed_at),
  first_name = COALESCE($3, first_name),
  last_name = COALESCE($4, last_name),
  is_email_verified = COALESCE($5, is_email_verified),
  phone_number = COALESCE($6, phone_number),
  profile_photo = COALESCE($7, profile_photo)
WHERE
  username = $8
RETURNING username, hashed_password, first_name, last_name, phone_number, profile_photo, email, is_admin, password_changed_at, created_at, is_email_verified, id, verification_code
`

type UpdateUserParams struct {
	HashedPassword    pgtype.Text        `json:"hashed_password"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	FirstName         pgtype.Text        `json:"first_name"`
	LastName          pgtype.Text        `json:"last_name"`
	IsEmailVerified   pgtype.Bool        `json:"is_email_verified"`
	PhoneNumber       pgtype.Text        `json:"phone_number"`
	ProfilePhoto      pgtype.Text        `json:"profile_photo"`
	Username          string             `json:"username"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.HashedPassword,
		arg.PasswordChangedAt,
		arg.FirstName,
		arg.LastName,
		arg.IsEmailVerified,
		arg.PhoneNumber,
		arg.ProfilePhoto,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfilePhoto,
		&i.Email,
		&i.IsAdmin,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
		&i.ID,
		&i.VerificationCode,
	)
	return i, err
}

const updateUserVerificationCode = `-- name: UpdateUserVerificationCode :one
UPDATE users
SET
  verification_code = COALESCE($1, verification_code)
WHERE
  email = $2
RETURNING username, hashed_password, first_name, last_name, phone_number, profile_photo, email, is_admin, password_changed_at, created_at, is_email_verified, id, verification_code
`

type UpdateUserVerificationCodeParams struct {
	VerificationCode pgtype.Text `json:"verification_code"`
	Email            string      `json:"email"`
}

func (q *Queries) UpdateUserVerificationCode(ctx context.Context, arg UpdateUserVerificationCodeParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserVerificationCode, arg.VerificationCode, arg.Email)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.ProfilePhoto,
		&i.Email,
		&i.IsAdmin,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
		&i.ID,
		&i.VerificationCode,
	)
	return i, err
}
