// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: rpc_list_collection.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        int32                  `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionRequest) Reset() {
	*x = ListCollectionRequest{}
	mi := &file_rpc_list_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionRequest) ProtoMessage() {}

func (x *ListCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_list_collection_proto_rawDescGZIP(), []int{0}
}

func (x *ListCollectionRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListCollectionRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    []*Collection          `protobuf:"bytes,1,rep,name=collection,proto3" json:"collection,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionResponse) Reset() {
	*x = ListCollectionResponse{}
	mi := &file_rpc_list_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionResponse) ProtoMessage() {}

func (x *ListCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_list_collection_proto_rawDescGZIP(), []int{1}
}

func (x *ListCollectionResponse) GetCollection() []*Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *ListCollectionResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_rpc_list_collection_proto protoreflect.FileDescriptor

const file_rpc_list_collection_proto_rawDesc = "" +
	"\n" +
	"\x19rpc_list_collection.proto\x12\x02pb\x1a\x10collection.proto\"M\n" +
	"\x15ListCollectionRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\x05R\x06pageId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"p\n" +
	"\x16ListCollectionResponse\x12.\n" +
	"\n" +
	"collection\x18\x01 \x03(\v2\x0e.pb.CollectionR\n" +
	"collection\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageTokenB*Z(github.com/Shegs-Emma/sisikemi_server/pbb\x06proto3"

var (
	file_rpc_list_collection_proto_rawDescOnce sync.Once
	file_rpc_list_collection_proto_rawDescData []byte
)

func file_rpc_list_collection_proto_rawDescGZIP() []byte {
	file_rpc_list_collection_proto_rawDescOnce.Do(func() {
		file_rpc_list_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_list_collection_proto_rawDesc), len(file_rpc_list_collection_proto_rawDesc)))
	})
	return file_rpc_list_collection_proto_rawDescData
}

var file_rpc_list_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_list_collection_proto_goTypes = []any{
	(*ListCollectionRequest)(nil),  // 0: pb.ListCollectionRequest
	(*ListCollectionResponse)(nil), // 1: pb.ListCollectionResponse
	(*Collection)(nil),             // 2: pb.Collection
}
var file_rpc_list_collection_proto_depIdxs = []int32{
	2, // 0: pb.ListCollectionResponse.collection:type_name -> pb.Collection
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_list_collection_proto_init() }
func file_rpc_list_collection_proto_init() {
	if File_rpc_list_collection_proto != nil {
		return
	}
	file_collection_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_list_collection_proto_rawDesc), len(file_rpc_list_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_list_collection_proto_goTypes,
		DependencyIndexes: file_rpc_list_collection_proto_depIdxs,
		MessageInfos:      file_rpc_list_collection_proto_msgTypes,
	}.Build()
	File_rpc_list_collection_proto = out.File
	file_rpc_list_collection_proto_goTypes = nil
	file_rpc_list_collection_proto_depIdxs = nil
}
