// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: rpc_image_upload.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message which carries the image file chunk
type UploadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`       // This is the image data in bytes
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"` // Optional, for sending the file name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_rpc_image_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_image_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_image_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *UploadImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// The response message after successful upload
type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_rpc_image_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_image_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_image_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImageResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

var File_rpc_image_upload_proto protoreflect.FileDescriptor

const file_rpc_image_upload_proto_rawDesc = "" +
	"\n" +
	"\x16rpc_image_upload.proto\x12\x02pb\x1a\vmedia.proto\x1a\x1fgoogle/api/field_behavior.proto\"P\n" +
	"\x12UploadImageRequest\x12\x19\n" +
	"\x05image\x18\x01 \x01(\fB\x03\xe0A\x02R\x05image\x12\x1f\n" +
	"\bfilename\x18\x02 \x01(\tB\x03\xe0A\x02R\bfilename\"6\n" +
	"\x13UploadImageResponse\x12\x1f\n" +
	"\x05media\x18\x01 \x01(\v2\t.pb.MediaR\x05mediaB*Z(github.com/Shegs-Emma/sisikemi_server/pbb\x06proto3"

var (
	file_rpc_image_upload_proto_rawDescOnce sync.Once
	file_rpc_image_upload_proto_rawDescData []byte
)

func file_rpc_image_upload_proto_rawDescGZIP() []byte {
	file_rpc_image_upload_proto_rawDescOnce.Do(func() {
		file_rpc_image_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_image_upload_proto_rawDesc), len(file_rpc_image_upload_proto_rawDesc)))
	})
	return file_rpc_image_upload_proto_rawDescData
}

var file_rpc_image_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_image_upload_proto_goTypes = []any{
	(*UploadImageRequest)(nil),  // 0: pb.UploadImageRequest
	(*UploadImageResponse)(nil), // 1: pb.UploadImageResponse
	(*Media)(nil),               // 2: pb.Media
}
var file_rpc_image_upload_proto_depIdxs = []int32{
	2, // 0: pb.UploadImageResponse.media:type_name -> pb.Media
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_image_upload_proto_init() }
func file_rpc_image_upload_proto_init() {
	if File_rpc_image_upload_proto != nil {
		return
	}
	file_media_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_image_upload_proto_rawDesc), len(file_rpc_image_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_image_upload_proto_goTypes,
		DependencyIndexes: file_rpc_image_upload_proto_depIdxs,
		MessageInfos:      file_rpc_image_upload_proto_msgTypes,
	}.Build()
	File_rpc_image_upload_proto = out.File
	file_rpc_image_upload_proto_goTypes = nil
	file_rpc_image_upload_proto_depIdxs = nil
}
