// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: rpc_create_collection.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCollectionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CollectionName        string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	CollectionDescription string                 `protobuf:"bytes,2,opt,name=collection_description,json=collectionDescription,proto3" json:"collection_description,omitempty"`
	ThumbnailImage        string                 `protobuf:"bytes,3,opt,name=thumbnail_image,json=thumbnailImage,proto3" json:"thumbnail_image,omitempty"`
	HeaderImage           string                 `protobuf:"bytes,4,opt,name=header_image,json=headerImage,proto3" json:"header_image,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_rpc_create_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_collection_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCollectionRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CreateCollectionRequest) GetCollectionDescription() string {
	if x != nil {
		return x.CollectionDescription
	}
	return ""
}

func (x *CreateCollectionRequest) GetThumbnailImage() string {
	if x != nil {
		return x.ThumbnailImage
	}
	return ""
}

func (x *CreateCollectionRequest) GetHeaderImage() string {
	if x != nil {
		return x.HeaderImage
	}
	return ""
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *Collection            `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_rpc_create_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_collection_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCollectionResponse) GetCollection() *Collection {
	if x != nil {
		return x.Collection
	}
	return nil
}

var File_rpc_create_collection_proto protoreflect.FileDescriptor

const file_rpc_create_collection_proto_rawDesc = "" +
	"\n" +
	"\x1brpc_create_collection.proto\x12\x02pb\x1a\x10collection.proto\"\xc5\x01\n" +
	"\x17CreateCollectionRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x125\n" +
	"\x16collection_description\x18\x02 \x01(\tR\x15collectionDescription\x12'\n" +
	"\x0fthumbnail_image\x18\x03 \x01(\tR\x0ethumbnailImage\x12!\n" +
	"\fheader_image\x18\x04 \x01(\tR\vheaderImage\"J\n" +
	"\x18CreateCollectionResponse\x12.\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x0e.pb.CollectionR\n" +
	"collectionB*Z(github.com/Shegs-Emma/sisikemi_server/pbb\x06proto3"

var (
	file_rpc_create_collection_proto_rawDescOnce sync.Once
	file_rpc_create_collection_proto_rawDescData []byte
)

func file_rpc_create_collection_proto_rawDescGZIP() []byte {
	file_rpc_create_collection_proto_rawDescOnce.Do(func() {
		file_rpc_create_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_collection_proto_rawDesc), len(file_rpc_create_collection_proto_rawDesc)))
	})
	return file_rpc_create_collection_proto_rawDescData
}

var file_rpc_create_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_collection_proto_goTypes = []any{
	(*CreateCollectionRequest)(nil),  // 0: pb.CreateCollectionRequest
	(*CreateCollectionResponse)(nil), // 1: pb.CreateCollectionResponse
	(*Collection)(nil),               // 2: pb.Collection
}
var file_rpc_create_collection_proto_depIdxs = []int32{
	2, // 0: pb.CreateCollectionResponse.collection:type_name -> pb.Collection
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_collection_proto_init() }
func file_rpc_create_collection_proto_init() {
	if File_rpc_create_collection_proto != nil {
		return
	}
	file_collection_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_collection_proto_rawDesc), len(file_rpc_create_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_collection_proto_goTypes,
		DependencyIndexes: file_rpc_create_collection_proto_depIdxs,
		MessageInfos:      file_rpc_create_collection_proto_msgTypes,
	}.Build()
	File_rpc_create_collection_proto = out.File
	file_rpc_create_collection_proto_goTypes = nil
	file_rpc_create_collection_proto_depIdxs = nil
}
