// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: rpc_update_product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateProductRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProductId          int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName        *string                `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3,oneof" json:"product_name,omitempty"`
	ProductDescription *string                `protobuf:"bytes,3,opt,name=product_description,json=productDescription,proto3,oneof" json:"product_description,omitempty"`
	ProductCode        *string                `protobuf:"bytes,4,opt,name=product_code,json=productCode,proto3,oneof" json:"product_code,omitempty"`
	Price              *int64                 `protobuf:"varint,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	SalePrice          *string                `protobuf:"bytes,6,opt,name=sale_price,json=salePrice,proto3,oneof" json:"sale_price,omitempty"`
	Collection         *int64                 `protobuf:"varint,7,opt,name=collection,proto3,oneof" json:"collection,omitempty"`
	Quantity           *int32                 `protobuf:"varint,8,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Color              []string               `protobuf:"bytes,9,rep,name=color,proto3" json:"color,omitempty"`
	Size               []string               `protobuf:"bytes,10,rep,name=size,proto3" json:"size,omitempty"`
	Status             *string                `protobuf:"bytes,11,opt,name=status,proto3,oneof" json:"status,omitempty"`
	MainImage          *string                `protobuf:"bytes,12,opt,name=main_image,json=mainImage,proto3,oneof" json:"main_image,omitempty"`
	OtherImage_1       *string                `protobuf:"bytes,13,opt,name=other_image_1,json=otherImage1,proto3,oneof" json:"other_image_1,omitempty"`
	OtherImage_2       *string                `protobuf:"bytes,14,opt,name=other_image_2,json=otherImage2,proto3,oneof" json:"other_image_2,omitempty"`
	OtherImage_3       *string                `protobuf:"bytes,15,opt,name=other_image_3,json=otherImage3,proto3,oneof" json:"other_image_3,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_rpc_update_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_rpc_update_product_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductRequest) GetProductName() string {
	if x != nil && x.ProductName != nil {
		return *x.ProductName
	}
	return ""
}

func (x *UpdateProductRequest) GetProductDescription() string {
	if x != nil && x.ProductDescription != nil {
		return *x.ProductDescription
	}
	return ""
}

func (x *UpdateProductRequest) GetProductCode() string {
	if x != nil && x.ProductCode != nil {
		return *x.ProductCode
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetSalePrice() string {
	if x != nil && x.SalePrice != nil {
		return *x.SalePrice
	}
	return ""
}

func (x *UpdateProductRequest) GetCollection() int64 {
	if x != nil && x.Collection != nil {
		return *x.Collection
	}
	return 0
}

func (x *UpdateProductRequest) GetQuantity() int32 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *UpdateProductRequest) GetColor() []string {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *UpdateProductRequest) GetSize() []string {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *UpdateProductRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateProductRequest) GetMainImage() string {
	if x != nil && x.MainImage != nil {
		return *x.MainImage
	}
	return ""
}

func (x *UpdateProductRequest) GetOtherImage_1() string {
	if x != nil && x.OtherImage_1 != nil {
		return *x.OtherImage_1
	}
	return ""
}

func (x *UpdateProductRequest) GetOtherImage_2() string {
	if x != nil && x.OtherImage_2 != nil {
		return *x.OtherImage_2
	}
	return ""
}

func (x *UpdateProductRequest) GetOtherImage_3() string {
	if x != nil && x.OtherImage_3 != nil {
		return *x.OtherImage_3
	}
	return ""
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_rpc_update_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_rpc_update_product_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_rpc_update_product_proto protoreflect.FileDescriptor

const file_rpc_update_product_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_update_product.proto\x12\x02pb\x1a\rproduct.proto\"\xe5\x05\n" +
	"\x14UpdateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12&\n" +
	"\fproduct_name\x18\x02 \x01(\tH\x00R\vproductName\x88\x01\x01\x124\n" +
	"\x13product_description\x18\x03 \x01(\tH\x01R\x12productDescription\x88\x01\x01\x12&\n" +
	"\fproduct_code\x18\x04 \x01(\tH\x02R\vproductCode\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x05 \x01(\x03H\x03R\x05price\x88\x01\x01\x12\"\n" +
	"\n" +
	"sale_price\x18\x06 \x01(\tH\x04R\tsalePrice\x88\x01\x01\x12#\n" +
	"\n" +
	"collection\x18\a \x01(\x03H\x05R\n" +
	"collection\x88\x01\x01\x12\x1f\n" +
	"\bquantity\x18\b \x01(\x05H\x06R\bquantity\x88\x01\x01\x12\x14\n" +
	"\x05color\x18\t \x03(\tR\x05color\x12\x12\n" +
	"\x04size\x18\n" +
	" \x03(\tR\x04size\x12\x1b\n" +
	"\x06status\x18\v \x01(\tH\aR\x06status\x88\x01\x01\x12\"\n" +
	"\n" +
	"main_image\x18\f \x01(\tH\bR\tmainImage\x88\x01\x01\x12'\n" +
	"\rother_image_1\x18\r \x01(\tH\tR\votherImage1\x88\x01\x01\x12'\n" +
	"\rother_image_2\x18\x0e \x01(\tH\n" +
	"R\votherImage2\x88\x01\x01\x12'\n" +
	"\rother_image_3\x18\x0f \x01(\tH\vR\votherImage3\x88\x01\x01B\x0f\n" +
	"\r_product_nameB\x16\n" +
	"\x14_product_descriptionB\x0f\n" +
	"\r_product_codeB\b\n" +
	"\x06_priceB\r\n" +
	"\v_sale_priceB\r\n" +
	"\v_collectionB\v\n" +
	"\t_quantityB\t\n" +
	"\a_statusB\r\n" +
	"\v_main_imageB\x10\n" +
	"\x0e_other_image_1B\x10\n" +
	"\x0e_other_image_2B\x10\n" +
	"\x0e_other_image_3\">\n" +
	"\x15UpdateProductResponse\x12%\n" +
	"\aproduct\x18\x01 \x01(\v2\v.pb.ProductR\aproductB*Z(github.com/Shegs-Emma/sisikemi_server/pbb\x06proto3"

var (
	file_rpc_update_product_proto_rawDescOnce sync.Once
	file_rpc_update_product_proto_rawDescData []byte
)

func file_rpc_update_product_proto_rawDescGZIP() []byte {
	file_rpc_update_product_proto_rawDescOnce.Do(func() {
		file_rpc_update_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_update_product_proto_rawDesc), len(file_rpc_update_product_proto_rawDesc)))
	})
	return file_rpc_update_product_proto_rawDescData
}

var file_rpc_update_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_update_product_proto_goTypes = []any{
	(*UpdateProductRequest)(nil),  // 0: pb.UpdateProductRequest
	(*UpdateProductResponse)(nil), // 1: pb.UpdateProductResponse
	(*Product)(nil),               // 2: pb.Product
}
var file_rpc_update_product_proto_depIdxs = []int32{
	2, // 0: pb.UpdateProductResponse.product:type_name -> pb.Product
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_update_product_proto_init() }
func file_rpc_update_product_proto_init() {
	if File_rpc_update_product_proto != nil {
		return
	}
	file_product_proto_init()
	file_rpc_update_product_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_update_product_proto_rawDesc), len(file_rpc_update_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_update_product_proto_goTypes,
		DependencyIndexes: file_rpc_update_product_proto_depIdxs,
		MessageInfos:      file_rpc_update_product_proto_msgTypes,
	}.Build()
	File_rpc_update_product_proto = out.File
	file_rpc_update_product_proto_goTypes = nil
	file_rpc_update_product_proto_depIdxs = nil
}
