// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.27.3
// source: rpc_create_cloudinary_media.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadCloudinaryImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageData []byte `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ImageName string `protobuf:"bytes,2,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
}

func (x *UploadCloudinaryImageRequest) Reset() {
	*x = UploadCloudinaryImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_cloudinary_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCloudinaryImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCloudinaryImageRequest) ProtoMessage() {}

func (x *UploadCloudinaryImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_cloudinary_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCloudinaryImageRequest.ProtoReflect.Descriptor instead.
func (*UploadCloudinaryImageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_cloudinary_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadCloudinaryImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *UploadCloudinaryImageRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type UploadCloudinaryImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Media *Media `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
}

func (x *UploadCloudinaryImageResponse) Reset() {
	*x = UploadCloudinaryImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_cloudinary_media_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCloudinaryImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCloudinaryImageResponse) ProtoMessage() {}

func (x *UploadCloudinaryImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_cloudinary_media_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCloudinaryImageResponse.ProtoReflect.Descriptor instead.
func (*UploadCloudinaryImageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_cloudinary_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadCloudinaryImageResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

var File_rpc_create_cloudinary_media_proto protoreflect.FileDescriptor

var file_rpc_create_cloudinary_media_proto_rawDesc = []byte{
	0x0a, 0x21, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x1c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43,
	0x6c, 0x6f, 0x75, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x09,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0a, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0,
	0x41, 0x02, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a,
	0x1d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x70, 0x62, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x42,
	0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65,
	0x63, 0x68, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x62,
	0x61, 0x6e, 0x6b, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_create_cloudinary_media_proto_rawDescOnce sync.Once
	file_rpc_create_cloudinary_media_proto_rawDescData = file_rpc_create_cloudinary_media_proto_rawDesc
)

func file_rpc_create_cloudinary_media_proto_rawDescGZIP() []byte {
	file_rpc_create_cloudinary_media_proto_rawDescOnce.Do(func() {
		file_rpc_create_cloudinary_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_cloudinary_media_proto_rawDescData)
	})
	return file_rpc_create_cloudinary_media_proto_rawDescData
}

var file_rpc_create_cloudinary_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_cloudinary_media_proto_goTypes = []interface{}{
	(*UploadCloudinaryImageRequest)(nil),  // 0: pb.UploadCloudinaryImageRequest
	(*UploadCloudinaryImageResponse)(nil), // 1: pb.UploadCloudinaryImageResponse
	(*Media)(nil),                         // 2: pb.Media
}
var file_rpc_create_cloudinary_media_proto_depIdxs = []int32{
	2, // 0: pb.UploadCloudinaryImageResponse.media:type_name -> pb.Media
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_cloudinary_media_proto_init() }
func file_rpc_create_cloudinary_media_proto_init() {
	if File_rpc_create_cloudinary_media_proto != nil {
		return
	}
	file_media_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_cloudinary_media_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCloudinaryImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_cloudinary_media_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCloudinaryImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_cloudinary_media_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_cloudinary_media_proto_goTypes,
		DependencyIndexes: file_rpc_create_cloudinary_media_proto_depIdxs,
		MessageInfos:      file_rpc_create_cloudinary_media_proto_msgTypes,
	}.Build()
	File_rpc_create_cloudinary_media_proto = out.File
	file_rpc_create_cloudinary_media_proto_rawDesc = nil
	file_rpc_create_cloudinary_media_proto_goTypes = nil
	file_rpc_create_cloudinary_media_proto_depIdxs = nil
}
