// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: rpc_get_media.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_rpc_get_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_media_proto_rawDescGZIP(), []int{0}
}

func (x *GetMediaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	mi := &file_rpc_get_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_media_proto_rawDescGZIP(), []int{1}
}

func (x *GetMediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

var File_rpc_get_media_proto protoreflect.FileDescriptor

const file_rpc_get_media_proto_rawDesc = "" +
	"\n" +
	"\x13rpc_get_media.proto\x12\x02pb\x1a\vmedia.proto\"!\n" +
	"\x0fGetMediaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"3\n" +
	"\x10GetMediaResponse\x12\x1f\n" +
	"\x05media\x18\x01 \x01(\v2\t.pb.MediaR\x05mediaB*Z(github.com/Shegs-Emma/sisikemi_server/pbb\x06proto3"

var (
	file_rpc_get_media_proto_rawDescOnce sync.Once
	file_rpc_get_media_proto_rawDescData []byte
)

func file_rpc_get_media_proto_rawDescGZIP() []byte {
	file_rpc_get_media_proto_rawDescOnce.Do(func() {
		file_rpc_get_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_media_proto_rawDesc), len(file_rpc_get_media_proto_rawDesc)))
	})
	return file_rpc_get_media_proto_rawDescData
}

var file_rpc_get_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_media_proto_goTypes = []any{
	(*GetMediaRequest)(nil),  // 0: pb.GetMediaRequest
	(*GetMediaResponse)(nil), // 1: pb.GetMediaResponse
	(*Media)(nil),            // 2: pb.Media
}
var file_rpc_get_media_proto_depIdxs = []int32{
	2, // 0: pb.GetMediaResponse.media:type_name -> pb.Media
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_media_proto_init() }
func file_rpc_get_media_proto_init() {
	if File_rpc_get_media_proto != nil {
		return
	}
	file_media_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_media_proto_rawDesc), len(file_rpc_get_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_media_proto_goTypes,
		DependencyIndexes: file_rpc_get_media_proto_depIdxs,
		MessageInfos:      file_rpc_get_media_proto_msgTypes,
	}.Build()
	File_rpc_get_media_proto = out.File
	file_rpc_get_media_proto_goTypes = nil
	file_rpc_get_media_proto_depIdxs = nil
}
