// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: rpc_create_media.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaRef      string                 `protobuf:"bytes,1,opt,name=media_ref,json=mediaRef,proto3" json:"media_ref,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	AwsId         string                 `protobuf:"bytes,3,opt,name=aws_id,json=awsId,proto3" json:"aws_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMediaRequest) Reset() {
	*x = CreateMediaRequest{}
	mi := &file_rpc_create_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaRequest) ProtoMessage() {}

func (x *CreateMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaRequest.ProtoReflect.Descriptor instead.
func (*CreateMediaRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_media_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMediaRequest) GetMediaRef() string {
	if x != nil {
		return x.MediaRef
	}
	return ""
}

func (x *CreateMediaRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateMediaRequest) GetAwsId() string {
	if x != nil {
		return x.AwsId
	}
	return ""
}

type CreateMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMediaResponse) Reset() {
	*x = CreateMediaResponse{}
	mi := &file_rpc_create_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaResponse) ProtoMessage() {}

func (x *CreateMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaResponse.ProtoReflect.Descriptor instead.
func (*CreateMediaResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_media_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

var File_rpc_create_media_proto protoreflect.FileDescriptor

const file_rpc_create_media_proto_rawDesc = "" +
	"\n" +
	"\x16rpc_create_media.proto\x12\x02pb\x1a\vmedia.proto\"Z\n" +
	"\x12CreateMediaRequest\x12\x1b\n" +
	"\tmedia_ref\x18\x01 \x01(\tR\bmediaRef\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x15\n" +
	"\x06aws_id\x18\x03 \x01(\tR\x05awsId\"6\n" +
	"\x13CreateMediaResponse\x12\x1f\n" +
	"\x05media\x18\x01 \x01(\v2\t.pb.MediaR\x05mediaB*Z(github.com/Shegs-Emma/sisikemi_server/pbb\x06proto3"

var (
	file_rpc_create_media_proto_rawDescOnce sync.Once
	file_rpc_create_media_proto_rawDescData []byte
)

func file_rpc_create_media_proto_rawDescGZIP() []byte {
	file_rpc_create_media_proto_rawDescOnce.Do(func() {
		file_rpc_create_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_media_proto_rawDesc), len(file_rpc_create_media_proto_rawDesc)))
	})
	return file_rpc_create_media_proto_rawDescData
}

var file_rpc_create_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_media_proto_goTypes = []any{
	(*CreateMediaRequest)(nil),  // 0: pb.CreateMediaRequest
	(*CreateMediaResponse)(nil), // 1: pb.CreateMediaResponse
	(*Media)(nil),               // 2: pb.Media
}
var file_rpc_create_media_proto_depIdxs = []int32{
	2, // 0: pb.CreateMediaResponse.media:type_name -> pb.Media
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_media_proto_init() }
func file_rpc_create_media_proto_init() {
	if File_rpc_create_media_proto != nil {
		return
	}
	file_media_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_media_proto_rawDesc), len(file_rpc_create_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_media_proto_goTypes,
		DependencyIndexes: file_rpc_create_media_proto_depIdxs,
		MessageInfos:      file_rpc_create_media_proto_msgTypes,
	}.Build()
	File_rpc_create_media_proto = out.File
	file_rpc_create_media_proto_goTypes = nil
	file_rpc_create_media_proto_depIdxs = nil
}
