// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: rpc_remove_cart_item.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartItemRequest) Reset() {
	*x = DeleteCartItemRequest{}
	mi := &file_rpc_remove_cart_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartItemRequest) ProtoMessage() {}

func (x *DeleteCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_remove_cart_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteCartItemRequest) Descriptor() ([]byte, []int) {
	return file_rpc_remove_cart_item_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteCartItemRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteCartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartItemResponse) Reset() {
	*x = DeleteCartItemResponse{}
	mi := &file_rpc_remove_cart_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartItemResponse) ProtoMessage() {}

func (x *DeleteCartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_remove_cart_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteCartItemResponse) Descriptor() ([]byte, []int) {
	return file_rpc_remove_cart_item_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteCartItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_remove_cart_item_proto protoreflect.FileDescriptor

const file_rpc_remove_cart_item_proto_rawDesc = "" +
	"\n" +
	"\x1arpc_remove_cart_item.proto\x12\x02pb\"6\n" +
	"\x15DeleteCartItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\"2\n" +
	"\x16DeleteCartItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB*Z(github.com/Shegs-Emma/sisikemi_server/pbb\x06proto3"

var (
	file_rpc_remove_cart_item_proto_rawDescOnce sync.Once
	file_rpc_remove_cart_item_proto_rawDescData []byte
)

func file_rpc_remove_cart_item_proto_rawDescGZIP() []byte {
	file_rpc_remove_cart_item_proto_rawDescOnce.Do(func() {
		file_rpc_remove_cart_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_remove_cart_item_proto_rawDesc), len(file_rpc_remove_cart_item_proto_rawDesc)))
	})
	return file_rpc_remove_cart_item_proto_rawDescData
}

var file_rpc_remove_cart_item_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_remove_cart_item_proto_goTypes = []any{
	(*DeleteCartItemRequest)(nil),  // 0: pb.DeleteCartItemRequest
	(*DeleteCartItemResponse)(nil), // 1: pb.DeleteCartItemResponse
}
var file_rpc_remove_cart_item_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_remove_cart_item_proto_init() }
func file_rpc_remove_cart_item_proto_init() {
	if File_rpc_remove_cart_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_remove_cart_item_proto_rawDesc), len(file_rpc_remove_cart_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_remove_cart_item_proto_goTypes,
		DependencyIndexes: file_rpc_remove_cart_item_proto_depIdxs,
		MessageInfos:      file_rpc_remove_cart_item_proto_msgTypes,
	}.Build()
	File_rpc_remove_cart_item_proto = out.File
	file_rpc_remove_cart_item_proto_goTypes = nil
	file_rpc_remove_cart_item_proto_depIdxs = nil
}
