// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: rpc_list_user_cart_items.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListUserCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageId   int32 `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListUserCartRequest) Reset() {
	*x = ListUserCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_list_user_cart_items_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCartRequest) ProtoMessage() {}

func (x *ListUserCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_user_cart_items_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCartRequest.ProtoReflect.Descriptor instead.
func (*ListUserCartRequest) Descriptor() ([]byte, []int) {
	return file_rpc_list_user_cart_items_proto_rawDescGZIP(), []int{0}
}

func (x *ListUserCartRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListUserCartRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cart          []*Cart `protobuf:"bytes,1,rep,name=cart,proto3" json:"cart,omitempty"`
	NextPageToken string  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *ListUserCartResponse) Reset() {
	*x = ListUserCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_list_user_cart_items_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCartResponse) ProtoMessage() {}

func (x *ListUserCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_user_cart_items_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCartResponse.ProtoReflect.Descriptor instead.
func (*ListUserCartResponse) Descriptor() ([]byte, []int) {
	return file_rpc_list_user_cart_items_proto_rawDescGZIP(), []int{1}
}

func (x *ListUserCartResponse) GetCart() []*Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *ListUserCartResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_rpc_list_user_cart_items_proto protoreflect.FileDescriptor

var file_rpc_list_user_cart_items_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x72, 0x70, 0x63, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x0a, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4b, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x5c, 0x0a,
	0x14, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x52, 0x04, 0x63,
	0x61, 0x72, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65,
	0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x25, 0x5a, 0x23, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x63, 0x68, 0x73, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x61, 0x6e, 0x6b, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_list_user_cart_items_proto_rawDescOnce sync.Once
	file_rpc_list_user_cart_items_proto_rawDescData = file_rpc_list_user_cart_items_proto_rawDesc
)

func file_rpc_list_user_cart_items_proto_rawDescGZIP() []byte {
	file_rpc_list_user_cart_items_proto_rawDescOnce.Do(func() {
		file_rpc_list_user_cart_items_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_list_user_cart_items_proto_rawDescData)
	})
	return file_rpc_list_user_cart_items_proto_rawDescData
}

var file_rpc_list_user_cart_items_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_list_user_cart_items_proto_goTypes = []any{
	(*ListUserCartRequest)(nil),  // 0: pb.ListUserCartRequest
	(*ListUserCartResponse)(nil), // 1: pb.ListUserCartResponse
	(*Cart)(nil),                 // 2: pb.Cart
}
var file_rpc_list_user_cart_items_proto_depIdxs = []int32{
	2, // 0: pb.ListUserCartResponse.cart:type_name -> pb.Cart
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_list_user_cart_items_proto_init() }
func file_rpc_list_user_cart_items_proto_init() {
	if File_rpc_list_user_cart_items_proto != nil {
		return
	}
	file_cart_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_list_user_cart_items_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListUserCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_list_user_cart_items_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListUserCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_list_user_cart_items_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_list_user_cart_items_proto_goTypes,
		DependencyIndexes: file_rpc_list_user_cart_items_proto_depIdxs,
		MessageInfos:      file_rpc_list_user_cart_items_proto_msgTypes,
	}.Build()
	File_rpc_list_user_cart_items_proto = out.File
	file_rpc_list_user_cart_items_proto_rawDesc = nil
	file_rpc_list_user_cart_items_proto_goTypes = nil
	file_rpc_list_user_cart_items_proto_depIdxs = nil
}
