// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: rpc_create_cart_item.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCartItemRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProductId       int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName     string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductPrice    int64                  `protobuf:"varint,3,opt,name=product_price,json=productPrice,proto3" json:"product_price,omitempty"`
	ProductQuantity int64                  `protobuf:"varint,4,opt,name=product_quantity,json=productQuantity,proto3" json:"product_quantity,omitempty"`
	ProductImage    string                 `protobuf:"bytes,5,opt,name=product_image,json=productImage,proto3" json:"product_image,omitempty"`
	ProductColor    string                 `protobuf:"bytes,6,opt,name=product_color,json=productColor,proto3" json:"product_color,omitempty"`
	ProductSize     string                 `protobuf:"bytes,7,opt,name=product_size,json=productSize,proto3" json:"product_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCartItemRequest) Reset() {
	*x = CreateCartItemRequest{}
	mi := &file_rpc_create_cart_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartItemRequest) ProtoMessage() {}

func (x *CreateCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_cart_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartItemRequest.ProtoReflect.Descriptor instead.
func (*CreateCartItemRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_cart_item_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCartItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateCartItemRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CreateCartItemRequest) GetProductPrice() int64 {
	if x != nil {
		return x.ProductPrice
	}
	return 0
}

func (x *CreateCartItemRequest) GetProductQuantity() int64 {
	if x != nil {
		return x.ProductQuantity
	}
	return 0
}

func (x *CreateCartItemRequest) GetProductImage() string {
	if x != nil {
		return x.ProductImage
	}
	return ""
}

func (x *CreateCartItemRequest) GetProductColor() string {
	if x != nil {
		return x.ProductColor
	}
	return ""
}

func (x *CreateCartItemRequest) GetProductSize() string {
	if x != nil {
		return x.ProductSize
	}
	return ""
}

type CreateCartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartItemResponse) Reset() {
	*x = CreateCartItemResponse{}
	mi := &file_rpc_create_cart_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartItemResponse) ProtoMessage() {}

func (x *CreateCartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_cart_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartItemResponse.ProtoReflect.Descriptor instead.
func (*CreateCartItemResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_cart_item_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCartItemResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

var File_rpc_create_cart_item_proto protoreflect.FileDescriptor

const file_rpc_create_cart_item_proto_rawDesc = "" +
	"\n" +
	"\x1arpc_create_cart_item.proto\x12\x02pb\x1a\n" +
	"cart.proto\"\x96\x02\n" +
	"\x15CreateCartItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12#\n" +
	"\rproduct_price\x18\x03 \x01(\x03R\fproductPrice\x12)\n" +
	"\x10product_quantity\x18\x04 \x01(\x03R\x0fproductQuantity\x12#\n" +
	"\rproduct_image\x18\x05 \x01(\tR\fproductImage\x12#\n" +
	"\rproduct_color\x18\x06 \x01(\tR\fproductColor\x12!\n" +
	"\fproduct_size\x18\a \x01(\tR\vproductSize\"6\n" +
	"\x16CreateCartItemResponse\x12\x1c\n" +
	"\x04cart\x18\x01 \x01(\v2\b.pb.CartR\x04cartB*Z(github.com/Shegs-Emma/sisikemi_server/pbb\x06proto3"

var (
	file_rpc_create_cart_item_proto_rawDescOnce sync.Once
	file_rpc_create_cart_item_proto_rawDescData []byte
)

func file_rpc_create_cart_item_proto_rawDescGZIP() []byte {
	file_rpc_create_cart_item_proto_rawDescOnce.Do(func() {
		file_rpc_create_cart_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_cart_item_proto_rawDesc), len(file_rpc_create_cart_item_proto_rawDesc)))
	})
	return file_rpc_create_cart_item_proto_rawDescData
}

var file_rpc_create_cart_item_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_cart_item_proto_goTypes = []any{
	(*CreateCartItemRequest)(nil),  // 0: pb.CreateCartItemRequest
	(*CreateCartItemResponse)(nil), // 1: pb.CreateCartItemResponse
	(*Cart)(nil),                   // 2: pb.Cart
}
var file_rpc_create_cart_item_proto_depIdxs = []int32{
	2, // 0: pb.CreateCartItemResponse.cart:type_name -> pb.Cart
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_cart_item_proto_init() }
func file_rpc_create_cart_item_proto_init() {
	if File_rpc_create_cart_item_proto != nil {
		return
	}
	file_cart_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_cart_item_proto_rawDesc), len(file_rpc_create_cart_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_cart_item_proto_goTypes,
		DependencyIndexes: file_rpc_create_cart_item_proto_depIdxs,
		MessageInfos:      file_rpc_create_cart_item_proto_msgTypes,
	}.Build()
	File_rpc_create_cart_item_proto = out.File
	file_rpc_create_cart_item_proto_goTypes = nil
	file_rpc_create_cart_item_proto_depIdxs = nil
}
