// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: rpc_list_user_cart_items.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListUserCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        int32                  `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCartRequest) Reset() {
	*x = ListUserCartRequest{}
	mi := &file_rpc_list_user_cart_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCartRequest) ProtoMessage() {}

func (x *ListUserCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_user_cart_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCartRequest.ProtoReflect.Descriptor instead.
func (*ListUserCartRequest) Descriptor() ([]byte, []int) {
	return file_rpc_list_user_cart_items_proto_rawDescGZIP(), []int{0}
}

func (x *ListUserCartRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListUserCartRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          []*Cart                `protobuf:"bytes,1,rep,name=cart,proto3" json:"cart,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCartResponse) Reset() {
	*x = ListUserCartResponse{}
	mi := &file_rpc_list_user_cart_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCartResponse) ProtoMessage() {}

func (x *ListUserCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_user_cart_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCartResponse.ProtoReflect.Descriptor instead.
func (*ListUserCartResponse) Descriptor() ([]byte, []int) {
	return file_rpc_list_user_cart_items_proto_rawDescGZIP(), []int{1}
}

func (x *ListUserCartResponse) GetCart() []*Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *ListUserCartResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_rpc_list_user_cart_items_proto protoreflect.FileDescriptor

const file_rpc_list_user_cart_items_proto_rawDesc = "" +
	"\n" +
	"\x1erpc_list_user_cart_items.proto\x12\x02pb\x1a\n" +
	"cart.proto\"K\n" +
	"\x13ListUserCartRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\x05R\x06pageId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\\\n" +
	"\x14ListUserCartResponse\x12\x1c\n" +
	"\x04cart\x18\x01 \x03(\v2\b.pb.CartR\x04cart\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageTokenB*Z(github.com/Shegs-Emma/sisikemi_server/pbb\x06proto3"

var (
	file_rpc_list_user_cart_items_proto_rawDescOnce sync.Once
	file_rpc_list_user_cart_items_proto_rawDescData []byte
)

func file_rpc_list_user_cart_items_proto_rawDescGZIP() []byte {
	file_rpc_list_user_cart_items_proto_rawDescOnce.Do(func() {
		file_rpc_list_user_cart_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_list_user_cart_items_proto_rawDesc), len(file_rpc_list_user_cart_items_proto_rawDesc)))
	})
	return file_rpc_list_user_cart_items_proto_rawDescData
}

var file_rpc_list_user_cart_items_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_list_user_cart_items_proto_goTypes = []any{
	(*ListUserCartRequest)(nil),  // 0: pb.ListUserCartRequest
	(*ListUserCartResponse)(nil), // 1: pb.ListUserCartResponse
	(*Cart)(nil),                 // 2: pb.Cart
}
var file_rpc_list_user_cart_items_proto_depIdxs = []int32{
	2, // 0: pb.ListUserCartResponse.cart:type_name -> pb.Cart
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_list_user_cart_items_proto_init() }
func file_rpc_list_user_cart_items_proto_init() {
	if File_rpc_list_user_cart_items_proto != nil {
		return
	}
	file_cart_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_list_user_cart_items_proto_rawDesc), len(file_rpc_list_user_cart_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_list_user_cart_items_proto_goTypes,
		DependencyIndexes: file_rpc_list_user_cart_items_proto_depIdxs,
		MessageInfos:      file_rpc_list_user_cart_items_proto_msgTypes,
	}.Build()
	File_rpc_list_user_cart_items_proto = out.File
	file_rpc_list_user_cart_items_proto_goTypes = nil
	file_rpc_list_user_cart_items_proto_depIdxs = nil
}
