// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: rpc_list_product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Collection    int64                  `protobuf:"varint,2,opt,name=collection,proto3" json:"collection,omitempty"`
	MinPrice      int32                  `protobuf:"varint,3,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      int32                  `protobuf:"varint,4,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortDir       string                 `protobuf:"bytes,6,opt,name=sort_dir,json=sortDir,proto3" json:"sort_dir,omitempty"`
	ProductName   string                 `protobuf:"bytes,7,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	PageId        int32                  `protobuf:"varint,8,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductRequest) Reset() {
	*x = ListProductRequest{}
	mi := &file_rpc_list_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductRequest) ProtoMessage() {}

func (x *ListProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductRequest.ProtoReflect.Descriptor instead.
func (*ListProductRequest) Descriptor() ([]byte, []int) {
	return file_rpc_list_product_proto_rawDescGZIP(), []int{0}
}

func (x *ListProductRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListProductRequest) GetCollection() int64 {
	if x != nil {
		return x.Collection
	}
	return 0
}

func (x *ListProductRequest) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ListProductRequest) GetMaxPrice() int32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ListProductRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListProductRequest) GetSortDir() string {
	if x != nil {
		return x.SortDir
	}
	return ""
}

func (x *ListProductRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ListProductRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListProductRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       []*Product             `protobuf:"bytes,1,rep,name=product,proto3" json:"product,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductResponse) Reset() {
	*x = ListProductResponse{}
	mi := &file_rpc_list_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductResponse) ProtoMessage() {}

func (x *ListProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductResponse.ProtoReflect.Descriptor instead.
func (*ListProductResponse) Descriptor() ([]byte, []int) {
	return file_rpc_list_product_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductResponse) GetProduct() []*Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *ListProductResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListProductResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListProductResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_rpc_list_product_proto protoreflect.FileDescriptor

const file_rpc_list_product_proto_rawDesc = "" +
	"\n" +
	"\x16rpc_list_product.proto\x12\x02pb\x1a\rproduct.proto\"\x93\x02\n" +
	"\x12ListProductRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\x03R\n" +
	"collection\x12\x1b\n" +
	"\tmin_price\x18\x03 \x01(\x05R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x04 \x01(\x05R\bmaxPrice\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\x12\x19\n" +
	"\bsort_dir\x18\x06 \x01(\tR\asortDir\x12!\n" +
	"\fproduct_name\x18\a \x01(\tR\vproductName\x12\x17\n" +
	"\apage_id\x18\b \x01(\x05R\x06pageId\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\"\xa6\x01\n" +
	"\x13ListProductResponse\x12%\n" +
	"\aproduct\x18\x01 \x03(\v2\v.pb.ProductR\aproduct\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCountB*Z(github.com/Shegs-Emma/sisikemi_server/pbb\x06proto3"

var (
	file_rpc_list_product_proto_rawDescOnce sync.Once
	file_rpc_list_product_proto_rawDescData []byte
)

func file_rpc_list_product_proto_rawDescGZIP() []byte {
	file_rpc_list_product_proto_rawDescOnce.Do(func() {
		file_rpc_list_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_list_product_proto_rawDesc), len(file_rpc_list_product_proto_rawDesc)))
	})
	return file_rpc_list_product_proto_rawDescData
}

var file_rpc_list_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_list_product_proto_goTypes = []any{
	(*ListProductRequest)(nil),  // 0: pb.ListProductRequest
	(*ListProductResponse)(nil), // 1: pb.ListProductResponse
	(*Product)(nil),             // 2: pb.Product
}
var file_rpc_list_product_proto_depIdxs = []int32{
	2, // 0: pb.ListProductResponse.product:type_name -> pb.Product
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_list_product_proto_init() }
func file_rpc_list_product_proto_init() {
	if File_rpc_list_product_proto != nil {
		return
	}
	file_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_list_product_proto_rawDesc), len(file_rpc_list_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_list_product_proto_goTypes,
		DependencyIndexes: file_rpc_list_product_proto_depIdxs,
		MessageInfos:      file_rpc_list_product_proto_msgTypes,
	}.Build()
	File_rpc_list_product_proto = out.File
	file_rpc_list_product_proto_goTypes = nil
	file_rpc_list_product_proto_depIdxs = nil
}
