// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: shippingAddress.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShippingAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      *User                  `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Town          string                 `protobuf:"bytes,5,opt,name=town,proto3" json:"town,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Landmark      string                 `protobuf:"bytes,7,opt,name=landmark,proto3" json:"landmark,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingAddress) Reset() {
	*x = ShippingAddress{}
	mi := &file_shippingAddress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingAddress) ProtoMessage() {}

func (x *ShippingAddress) ProtoReflect() protoreflect.Message {
	mi := &file_shippingAddress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingAddress.ProtoReflect.Descriptor instead.
func (*ShippingAddress) Descriptor() ([]byte, []int) {
	return file_shippingAddress_proto_rawDescGZIP(), []int{0}
}

func (x *ShippingAddress) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShippingAddress) GetUsername() *User {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *ShippingAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ShippingAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ShippingAddress) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *ShippingAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *ShippingAddress) GetLandmark() string {
	if x != nil {
		return x.Landmark
	}
	return ""
}

func (x *ShippingAddress) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_shippingAddress_proto protoreflect.FileDescriptor

const file_shippingAddress_proto_rawDesc = "" +
	"\n" +
	"\x15shippingAddress.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"user.proto\"\x87\x02\n" +
	"\x0fShippingAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\busername\x18\x02 \x01(\v2\b.pb.UserR\busername\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04town\x18\x05 \x01(\tR\x04town\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\x12\x1a\n" +
	"\blandmark\x18\a \x01(\tR\blandmark\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB*Z(github.com/Shegs-Emma/sisikemi_server/pbb\x06proto3"

var (
	file_shippingAddress_proto_rawDescOnce sync.Once
	file_shippingAddress_proto_rawDescData []byte
)

func file_shippingAddress_proto_rawDescGZIP() []byte {
	file_shippingAddress_proto_rawDescOnce.Do(func() {
		file_shippingAddress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shippingAddress_proto_rawDesc), len(file_shippingAddress_proto_rawDesc)))
	})
	return file_shippingAddress_proto_rawDescData
}

var file_shippingAddress_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shippingAddress_proto_goTypes = []any{
	(*ShippingAddress)(nil),       // 0: pb.ShippingAddress
	(*User)(nil),                  // 1: pb.User
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_shippingAddress_proto_depIdxs = []int32{
	1, // 0: pb.ShippingAddress.username:type_name -> pb.User
	2, // 1: pb.ShippingAddress.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shippingAddress_proto_init() }
func file_shippingAddress_proto_init() {
	if File_shippingAddress_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shippingAddress_proto_rawDesc), len(file_shippingAddress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shippingAddress_proto_goTypes,
		DependencyIndexes: file_shippingAddress_proto_depIdxs,
		MessageInfos:      file_shippingAddress_proto_msgTypes,
	}.Build()
	File_shippingAddress_proto = out.File
	file_shippingAddress_proto_goTypes = nil
	file_shippingAddress_proto_depIdxs = nil
}
